### ISSUE TITLE
In 03_setup_env.md, run env setup after interactive job start

### ISSUE THREAD

**Issue by thompsonmj** [Imageomics/snakemake-workshop#8]
The `setup_env.sh` script should be run *after* starting the interactive session on a worker node. 

When I run this script first, then start the job, the env gets deactivated.

**Comment by johnbradley** [comment]
Are you running setup_env.sh like so: `. setup_env`. The period at the beginning adds it to your shell. For me the environment is persisted when I start an interactive session.

**Comment by thompsonmj** [comment]
Yeah, that's how I enter it. The modules stay loaded, but the environment goes back to base after starting the interactive job.

**Comment by johnbradley** [comment]
That's interesting. I'm fine with swapping the order in the instructions. It's just odd that your environment variables aren't persisted.
